### ISSUE TITLE
Loading stalls in 1.16.1 with Tech Reborn

### ISSUE THREAD

**Issue by Dakedres** [Virtuoel/Towelette#22]
If Towlette and Tech Reborn are loaded alongside each other in 1.16, loading will stall the moment Tech Reborn is finished with some pretty decent CPU usage, I've left it to load for several minutes with nothing new to the log.

Log: https://paste.ee/p/1ehGv
Fabric loader version: 0.8.8-build.202
Fabric API version: 0.13.1-build.370

**Comment by muzikbike** [comment]
I've noticed similar behaviour with hwyla (with flowing waterlogging active, but enough ram dedicated anyway), havent tested it without it though.

**Comment by Onixiya** [comment]
I've asked about this and apparently its something to do with how techreborn handles fluids and something about that just doesn't agree with towelette. At least i'm not the only experiencing this problem

**Comment by Virtuoel** [comment]
Since TechReborn adds fluids, Towelette attempts to make them be usable for fluidlogging. This unfortunately can take up a lot of memory and reduce load times since TechReborn has many many fluids.

The latest Towelette update adds a config option for blacklisting fluids from being used for fluidlogging by specifying only the fluid's mod ID instead of all the fluid IDs individually. 
You should now be able to add `"techreborn"` to the `blacklistedFluidModIds` section in the config.
