### ISSUE TITLE
Allow fluidlogging with bubble columns

### ISSUE THREAD

**Issue by muzikbike** [Virtuoel/Towelette#4]
This would also effectively work as a fix for MC-127141.

**Comment by Virtuoel** [comment]
This is out of scope for Towelette since bubble columns are not their own fluid. Towelette does not add any fluids, but if another mod were to add a bubble column fluid, Towelette would automatically allow fluidlogging with it. 

I might revisit this if I look into fluid layer stuff, but that's not a high priority currently.
