### ISSUE TITLE
waterlogs blocks on servers with water and lava and rebstone

### ISSUE THREAD

**Issue by t63r** [Virtuoel/Towelette#7]
i was trying to play a server this happened

**Comment by Virtuoel** [comment]
I think you may have forgotten a screenshot or something, but if I'm understanding the issue correctly you're probably connecting to a server that does not have Towelette installed. Since this mod makes changes to many existing blocks to allow for waterlogging with any fluid, both the client and server will need to have it installed, otherwise issues may occur.
